# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import QDate, QDateTime, QTime, Qt


class Ui_Dialog_1(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, Dialog_1):
        Dialog_1.setObjectName("Setting DateTime")
        Dialog_1.resize(1920, 1080)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 120, 431, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dateEdit.setSizeIncrement(QtCore.QSize(0, 0))
        self.dateEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateEdit.setFont(font)
        self.dateEdit.setDisplayFormat("yyyy/MM/dd")
        self.dateEdit.setMaximumDateTime(
            QtCore.QDateTime(QtCore.QDate(2030, 12, 31),
                             QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(
            QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.dateChanged.connect(self.onDateChanged)
        self.verticalLayout.addWidget(self.dateEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.timeEdit.setFont(font)
        self.timeEdit.setDisplayFormat("HH:mm:ss")
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.timeChanged.connect(self.onTimeChanged)
        self.verticalLayout.addWidget(self.timeEdit)
        self.pushButton = QtWidgets.QPushButton(Dialog_1)
        self.pushButton.setGeometry(QtCore.QRect(380, 401, 113, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onButtonClick)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog_1)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 113, 40))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(Dialog_1.mainv)

        self.retranslateUi(Dialog_1)
        QtCore.QMetaObject.connectSlotsByName(Dialog_1)

    def retranslateUi(self, Dialog_1):
        _translate = QtCore.QCoreApplication.translate
        Dialog_1.setWindowTitle(_translate("Dialog_1", "Dialog_1"))
        self.label.setText(_translate("Dialog_1", "選擇日期"))
        self.label_2.setText(_translate("Dialog_1", "選擇時間"))
        self.pushButton.setText(_translate("Dialog_1", "套用"))
        self.pushButton_4.setText(_translate("Dialog_1", "返回"))

    def onDateChanged(self, date):
        print(date)
        # 时间发生改变时执行
    def onTimeChanged(self, time):
        print(time)

    def onButtonClick(self):
        date = self.dateEdit.date()
        ForDate = date.toString(Qt.ISODate)
        Time = self.timeEdit.time()
        ForTime = Time.toString(Qt.DefaultLocaleLongDate)
        dd = ForDate + ForTime
        GMT_FORMAT = '%Y-%m-%d%I:%M:%S %p CST'
        FormatDateTime = datetime.strptime(dd, GMT_FORMAT)
        command = "sudo date -s" + '"' + str(FormatDateTime) + '"'
        print(command)
        rep = os.popen(command)
